# Generated by Django 3.0.6 on 2020-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(max_length=10)),
                ('offerprice', models.FloatField(max_length=10)),
                ('amount', models.CharField(choices=[('100g', '100g'), ('250g', '250g'), ('500g', '500g'), ('1Kg', '1Kg'), ('2Kg', '2Kg'), ('5Kg', '5Kg'), ('10Kg', '10Kg')], max_length=20)),
                ('image', models.ImageField(upload_to='productspics')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
