# Generated by Django 3.0.6 on 2020-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20200601_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('bakery', 'bakery'), ('dairy', 'dairy'), ('deepfreezed', 'deepfreezed'), ('grocery', 'grocery')], default=0, max_length=60),
            preserve_default=False,
        ),
    ]
