# Generated by Django 3.0.6 on 2020-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('productcode', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=60)),
                ('price', models.FloatField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='cartimages')),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
