# Generated by Django 3.0.6 on 2020-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
            ],
        ),
    ]
